version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  heroes:
    image: heroes:latest
    depends_on:
      - "mongo"
    ports:
      - 8080:8080